Linux-Operation0605/app/maillog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

Linux-Operation0605/operation/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^operation/', include('operation.proxy_urls')),
]

Linux-Operation0605/app/maillog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import time
import json
from django.db import models
from django.template import Template, Context
from app.core.models import Domain
from lib.formats import dict_compatibility, safe_format

from app.maillog import constants


class MailLog(models.Model):
    """
    邮件收发log
    """
    main_id = models.CharField(u'任务主ID', max_length=30, null=False, blank=False)
    domain_id = models.IntegerField(u"域名ID", default=0, db_index=True, null=False, blank=False,help_text=u"域名ID")
    mailbox_id = models.IntegerField(u"邮箱ID", default=0, db_index=True, null=False, blank=False,help_text=u"邮箱ID")
    type = models.CharField(u'发送类型', max_length=10, choices=constants.MAILLOG_TYPE, default='out', null=False, blank=False)
    send_mail = models.CharField(u'发信人', max_length=100, blank=False)
    recv_mail = models.CharField(u'收信人', db_column='rcv_mail', max_length=100, blank=False)
    subject = models.CharField(u'主题', max_length=200, blank=False)
    size = models.IntegerField(u"邮件大小", default=0, db_index=False, blank=False,help_text=u"邮件大小")
    attachment = models.CharField(u'附件名称', max_length=3000, blank=False)
    attachment_size = models.IntegerField(u"附件大小", default=0, db_index=False, blank=False, help_text=u"附件大小")
    result = models.CharField(u'结果', max_length=2, choices=constants.MAILLOG_RESULT, default=-1, null=False, blank=False)
    description = models.TextField(u"描述", null=True, blank=True)
    send_time = models.DateTimeField(u"发信时间", null=True, blank=False)
    recv_time = models.DateTimeField(u" 收信时间", null=True, blank=False)
    senderip = models.CharField(u'发信IP', max_length=20, null=True, blank=False)
    status = models.CharField(u'收发状态', max_length=20, null=True, blank=False)
    rcv_server = models.CharField(u'接收服务器', max_length=100, null=True, blank=False)
    folder = models.CharField(u'投递位置', max_length=100, null=True, blank=False)
    remark = models.CharField(u'备注', max_length=200, null=True, blank=False)

    class Meta:
        db_table = 'core_mail_log'
        managed = False

    @property
    def get_type(self):
        if self.type == "in":
            return u"收信"
        else:
            return u"发信"

    @property
    def get_result(self):
        return str(self.result)

    @property
    def get_time(self):
        if not self.recv_time:
            if self.send_time:
                return self.send_time.strftime('%Y-%m-%d %H:%M:%S')
            return "unknown"
        return self.recv_time.strftime('%Y-%m-%d %H:%M:%S')

    @property
    def get_username(self):
        if self.type == "in":
            l = self.recv_mail.split("@")
        else:
            l = self.send_mail.split("@")
        if l:
            return l[0]
        return "unknown"

    @property
    def get_attach_size(self):
        size = round(int(self.attachment_size)*1.0/(1024*1024),2)
        return size

class LogReport(models.Model):
    domain_id = models.IntegerField(u"域名ID", default=0, db_index=True, null=False, blank=False,help_text=u"域名ID")
    mailbox_id = models.IntegerField(u"邮箱ID", default=0, db_index=True, null=False, blank=False,help_text=u"邮箱ID")
    type = models.CharField(u'记录类型', max_length=10, choices=constants.MAILLOG_TYPE, default='out', null=False, blank=False)
    key = models.CharField(u'键值', max_length=200, blank=False)
    data = models.CharField(u'数据', max_length=2000, blank=False, null=True)
    last_update = models.DateTimeField(u"更新时间", null=False, blank=False)

    class Meta:
        db_table = 'ext_log_report'
        managed = False

    @staticmethod
    def get_cache(domain_id,mailbox_id,type,key):
        obj = LogReport.objects.filter(domain_id=domain_id,mailbox_id=mailbox_id,type=type,key=key).first()
        if not obj or not obj.data:
            return {}
        data = json.loads(obj.data)
        return data

    @staticmethod
    def save_cache(domain_id,mailbox_id,type,key,data):
        obj, _created = LogReport.objects.get_or_create(domain_id=domain_id,mailbox_id=mailbox_id,type=type,key=key)

        data = json.dumps( data )
        obj.domain_id = domain_id
        obj.mailbox_id = mailbox_id
        obj.type = type
        obj.key = key
        obj.data = data
        obj.last_update = time.strftime("%Y-%m-%d %H:%M:%S")
        obj.save()

class LogActive(models.Model):

    domain_id = models.IntegerField(u"域名ID", default=0, db_index=True, null=False, blank=False,help_text=u"域名ID")
    mailbox_id = models.IntegerField(u"邮箱ID", default=0, db_index=True, null=False, blank=False,help_text=u"邮箱ID")
    key = models.CharField(u'键值', max_length=200, blank=False)

    total_count = models.IntegerField(u"总数量", default=0, db_index=True, null=False, blank=False,help_text=u"总数量")
    total_flow = models.IntegerField(u"总流量", default=0, db_index=True, null=False, blank=False,help_text=u"总流量")

    in_count = models.IntegerField(u"收信数量", default=0, db_index=True, null=False, blank=False,help_text=u"收信数量")
    in_flow = models.IntegerField(u"收信流量", default=0, db_index=True, null=False, blank=False,help_text=u"收信流量")

    success_count = models.IntegerField(u"成功数量", default=0, db_index=True, null=False, blank=False,help_text=u"成功数量")
    success_flow = models.IntegerField(u"成功流量", default=0, db_index=True, null=False, blank=False,help_text=u"成功流量")

    spam_count = models.IntegerField(u"垃圾数量", default=0, db_index=True, null=False, blank=False,help_text=u"垃圾数量")
    spam_flow = models.IntegerField(u"垃圾流量", default=0, db_index=True, null=False, blank=False,help_text=u"垃圾流量")

    spam_ratio = models.CharField(u'垃圾比率', max_length=10, blank=False)
    success_ratio = models.CharField(u'成功比率', max_length=10, blank=False)

    class Meta:
        db_table = 'ext_log_active'
        managed = False

Linux-Operation0605/app/maillog/forms.py
# -*- coding: utf-8 -*-
#
import json
from django import forms
from lib.forms import BaseFied, DotDict
from app.core.models import Mailbox, Domain, CoreAlias, DomainAttr

from lib import validators
from lib.formats import dict_compatibility
from lib.tools import clear_redis_cache

from django.utils.translation import ugettext_lazy as _
from app.maillog import constants
from app.core.models import DomainAttr, Mailbox, Department
from app.core.constants import MAILBOX_SEND_PERMIT,MAILBOX_RECV_PERMIT

import time
import copy

def get_department_list():
    l = [(u"0",u"所有部门")]
    for obj in Department.objects.all():
        l.append( (obj.id,obj.title) )
    return tuple(l)

class MailLogSearchForm(forms.Form):

    type = forms.ChoiceField(label=u'发送类型', choices=constants.MAILLOG_TYPE, required=False, initial="in")
    start_time = forms.DateTimeField(label=u'开始时间', required=False, widget=forms.DateTimeInput(attrs={'size':12}))
    end_time = forms.DateTimeField(label=u'结束时间', required=False, widget=forms.DateTimeInput(attrs={'size':12}))
    max_attach = forms.FloatField(label=u'最大附件', required=False, widget=forms.NumberInput(attrs={"id":"id_max_attach",'size':12, 'placeholder': u""}))
    min_attach = forms.FloatField(label=u'最小附件', required=False, widget=forms.NumberInput(attrs={"id":"id_min_attach",'size':12, 'placeholder': u""}))

    send_mail = forms.CharField(label=u'发信人', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_send_mail",'size':12, 'placeholder': u""}))
    recv_mail = forms.CharField(label=u'收信人', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_recv_mail",'size':12, 'placeholder': u""}))
    senderip = forms.CharField(label=u'发信服务器', max_length=100, required=False, widget=forms.TextInput(attrs={'size':12, 'placeholder': u""}))
    rcv_server = forms.CharField(label=u'收件服务器', max_length=100, required=False, widget=forms.TextInput(attrs={'size':12, 'placeholder': u""}))
    username = forms.CharField(label=u'用户名', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_username",'size':12, 'placeholder': u""}))
    text = forms.CharField(label=u'标题/发件邮箱/收件邮箱/附件名称', max_length=200, required=False, widget=forms.TextInput(attrs={'size':12, 'placeholder': u""}))

    @property
    def get_start_time(self):
        return self.data.get("start_time","")

    @property
    def get_end_time(self):
        return self.data.get("end_time","")

    @property
    def get_senderip(self):
        return self.data.get("senderip","")

    @property
    def get_rcv_server(self):
        return self.data.get("rcv_server","")

    @property
    def get_text(self):
        return self.data.get("text","")

class MailboxStatForm(forms.Form):

    username = forms.CharField(label=u'用户名', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_username",'size':12, 'placeholder': u""}))
    name = forms.CharField(label=u'用户姓名', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_name",'size':12, 'placeholder': u""}))
    quota = forms.CharField(label=u'邮箱容量', max_length=100, required=False, widget=forms.NumberInput(attrs={"id":"id_quota",'size':12, 'placeholder': u""}))
    netdisk_quota = forms.CharField(label=u'网络硬盘容量', max_length=100, required=False, widget=forms.NumberInput(attrs={"id":"id_netdisk",'size':12, 'placeholder': u""}))

    send_permit = forms.ChoiceField(label=u'发送权限', required=False, choices=MAILBOX_SEND_PERMIT, widget=forms.Select(attrs={"id":"id_send_permit",'size':1}))
    recv_permit = forms.ChoiceField(label=u'接收权限', required=False, choices=MAILBOX_RECV_PERMIT, widget=forms.Select(attrs={"id":"id_recv_permit",'size':1}))

    department = forms.CharField(label=u'部门', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_department",'size':12, 'placeholder': u""}))
    position = forms.CharField(label=u'职位', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_position",'size':12, 'placeholder': u""}))
    worknumber = forms.CharField(label=u'工号', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_worknumber",'size':12, 'placeholder': u""}))

class ActiveUserStatForm(forms.Form):

    dept_list = get_department_list()
    department = forms.ChoiceField(label=u'部门', required=False, choices=dept_list, widget=forms.Select(attrs={"id":"id_department",'size':1, 'placeholder': u""}))
    username = forms.CharField(label=u'用户名', max_length=100, required=False, widget=forms.TextInput(attrs={"id":"id_username",'size':12, 'placeholder': u""}))
    showmax = forms.CharField(label=u'用户数', max_length=100, required=False, widget=forms.NumberInput(attrs={"id":"id_showmax",'size':12, 'placeholder': u""}))

Linux-Operation0605/app/maillog/templates/maillog/include/active_user.html
{% load i18n %}
{% load static %}

<div class="row">
    <div class="col-lg-12" style="margin-bottom: 10px">
        <div class="">
            <form id="search_form" class="form-inline" role="form" action="" style="text-align: left">
                <table class="table">
                <tr>
                    <th class="text-right">用户名: </th> <th>{{ form.username }} </th>
                    <th class="text-right">部门: </th> <th class="max-width-th">{{ form.department }} </th>
                    <th class="text-right">开始日期: </th>
                    <th >
                        <select name="date_select" id="id_date_select" size="1">
                        {% for d,name in date_select %}
                             <option value="{{ d }}" {% if d == date_value %} selected {% endif %}>{{ name }}</option>
                        {% endfor %}
                    </th>
                    <th class="text-right">结束日期: </th>
                    <th >
                        <select name="date_select2" id="id_date_select2" size="1">
                        {% for d,name in date_select2 %}
                             <option value="{{ d }}" {% if d == date_value2 %} selected {% endif %}>{{ name }}</option>
                        {% endfor %}
                        </th>
                    <th class="text-right">用户数: </th> <th>{{ form.showmax }} </th>
                </tr>
                </table>

                <input type="hidden" name="d" id="id_selectdomain" value="{{ domain.domain }}" />
                <button type="submit" class="btn btn-primary btn-sm">查询</button>
                <button type="reset" class="btn btn-primary btn-sm" onClick="resetSearch()">重置查询</button>
                <button type="reset" class="btn btn-primary btn-sm" onClick="exportLog()">导出日志</button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <form id="id_form" action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" id="id" />
            <input type="hidden" name="status" id="status" />
            <input type="hidden" name="ids" id="ids" />
        </form>
        <table id="ajax-table" class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th width="4%">{% trans "序号" %}</th>
                <th>{% trans "用户名称" %}</th>
                <th>{% trans "邮件数量" %}</th>
                <th>{% trans "总流量" %}</th>
                <th>{% trans "入站数量" %}</th>
                <th>{% trans "入站流量" %}</th>
                <th>{% trans "垃圾过滤数量" %}</th>
                <th>{% trans "垃圾过滤流量" %}</th>
                <th>{% trans "出站数量" %}</th>
                <th>{% trans "出站流量" %}</th>
                <th>{% trans "成功数量" %}</th>
                <th>{% trans "成功流量" %}</th>
                <th>{% trans "失败数量" %}</th>
                <th>{% trans "失败流量" %}</th>
                <th>{% trans "垃圾率" %}</th>
                <th>{% trans "出站成功率" %}</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

Linux-Operation0605/app/maillog/templates/maillog/include/mailbox_stat.html
{% load i18n %}
{% load static %}

<div class="row">
    <div class="col-lg-12" style="margin-bottom: 10px">
        <div >
            <form id="search_form" class="form-horizontal" role="form" action="" style="text-align: left">

                <table class="table" border="0">
                    <tr>
                        <th class="text-right">用户名: </th> <th>{{ form.username }} </th>
                        <th class="text-right">用户姓名: </th> <th>{{ form.name }} </th>
                        <th class="text-right">部门: </th> <th>{{ form.department }} </th>
                        <th class="text-right">职位: </th> <th>{{ form.position }} </th>
                        <th class="text-right">工号: </th> <th>{{ form.worknumber }} </th>
                    </tr>
                    <tr>
                        <th class="text-right">邮箱容量: </th> <th>{{ form.quota }} </th>
                        <th class="text-right">网络硬盘容量: </th> <th>{{ form.netdisk_quota }} </th>
                        <th class="text-right">发送权限: </th> <th>{{ form.send_permit }} </th>
                        <th class="text-right">接收权限: </th> <th>{{ form.recv_permit }} </th>
                    </tr>
                </table>


                <input type="hidden" name="d" id="id_selectdomain" value="{{ domain.domain }}" />
                <button type="submit" class="btn btn-primary btn-sm" onClick="startSearch()">查询</button>
                <button type="reset" class="btn btn-primary btn-sm" onClick="resetSearch()">重置查询</button>
                <button type="button" class="btn btn-primary btn-sm" onClick="exportLog()">导出日志</button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 ">
        <form id="id_form" action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" id="id" />
            <input type="hidden" name="status" id="status" />
            <input type="hidden" name="ids" id="ids" />
        </form>
        <div class="table-responsive">
            <table id="ajax-table" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th width="4%">{% trans "序号" %}</th>
                    <th>{% trans "用户名称" %}</th>
                    <th>{% trans "用户姓名" %}</th>
                    <th>{% trans "部门" %}</th>
                    <th>{% trans "职位" %}</th>
                    <th>{% trans "工号" %}</th>
                    <th>{% trans "发送权限" %}</th>
                    <th>{% trans "接收权限" %}</th>
                    <th>{% trans "邮箱容量" %}</th>
                    <th>{% trans "网络硬盘容量" %}</th>
                    <th>{% trans "已用邮箱容量" %}</th>
                    <th>{% trans "网页最后登录时间" %}</th>
                    <th>{% trans "客户端最后登录时间" %}</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

    </div>
</div>

Linux-Operation0605/app/maillog/templates/maillog/include/maillog.html
{% load i18n %}
{% load static %}

<div class="row">
    <div class="col-lg-12" style="margin-bottom: 10px">
        <div class="">
            <form id="search_form" class="form-inline" role="form" action="" style="text-align: left">
                <table class="table">
                <tr>
                <th class="text-right">类型: </th><th>{{ form.type }} </th>
                <th class="text-right">用户名: </th> <th>{{ form.username }} </th>
                <th class="text-right">最大附件: </th> <th>{{ form.max_attach }} </th>
                <th class="text-right">最小附件: </th> <th>{{ form.min_attach }} </th>
                </tr>
                <tr>
                    <th class="text-right">发信人: </th> <th>{{ form.send_mail }} </th>
                    <th class="text-right">收信人: </th> <th>{{ form.recv_mail }} </th>
                    <th class="text-right" >发信服务器: </th>
                    <th>
                         <input type="text" name="senderip" id="id_senderip" value="{{ form.get_senderip }}" size="16" class="textinput"  />
                    </th>
                    <th class="text-right">收信服务器: </th>
                    <th>
                         <input type="text" name="rcv_server" id="id_rcv_server" value="{{ form.get_rcv_server }}" size="16" class="textinput"  />
                    </th>
                </tr>
                <tr>
                    <th class="text-right">开始时间: </th>
                    <th>
                         <input type="text" name="start_time" id="id_start_time" value="{{ form.get_start_time }}" readonly="" size="16" data-date-format="yyyy-mm-dd hh:ii:00" class="dateinput" />
                    </th>
                    <th class="text-right">结束时间: </th>
                    <th>
                         <input type="text" name="end_time" id="id_end_time" value="{{ form.get_end_time }}" readonly="" size="16" data-date-format="yyyy-mm-dd hh:ii:00" class="dateinput"  />
                    </th>
                    <th class="text-right">标题/附件: </th>
                    <th>
                        <input type="text" name="text" id="id_text" value="{{ form.get_text }}" size="16" class="textinput" />
                    </th>
                    <th></th>
                    <th></th>
                </tr>
                </table>

                <input type="hidden" name="d" id="id_selectdomain" value="{{ domain.domain }}" />
                <button type="submit" class="btn btn-primary btn-sm">查询</button>
                <button type="reset" class="btn btn-primary btn-sm" onClick="resetSearch()">重置查询</button>
            </form>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <form id="id_form" action="" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" id="id" />
            <input type="hidden" name="status" id="status" />
            <input type="hidden" name="ids" id="ids" />
        </form>
        <div class="table-responsive">
            <table id="ajax-table" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th width="4%">{% trans "序号" %}</th>
                    <th>{% trans "时间" %}</th>
                    <th>{% trans "用户名" %}</th>
                    <th>{% trans "类型" %}</th>
                    <th>{% trans "发件邮箱" %}</th>
                    <th>{% trans "收件邮箱" %}</th>
                    <th>{% trans "发件服务器" %}</th>
                    <th>{% trans "收件服务器" %}</th>
                    <th>{% trans "邮件标题" %}</th>
                    <th>{% trans "附件名称" %}</th>
                    <th>{% trans "附件大小" %}</th>
                    <th>{% trans "投递位置" %}</th>
                    <th>{% trans "结果" %}</th>
                    <th>{% trans "投递提示" %}</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

    </div>
</div>