Linux-Operation0605/app/maintain/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from app.maintain import views

urlpatterns = [
    # url(r'^ssl/$', views.sslView, name='ssl_maintain'),
    # url(r'^ssl/enable$', views.sslEnableView, name='sslEnableView'),
    # url(r'^ssl/private$', views.sslPrivateView, name='sslPrivateView'),
    # url(r'^ssl/sign$', views.sslSignatureView, name='sslSignatureView'),
    # url(r'^ssl/cert$', views.sslCertView, name='sslCertView'),
    url(r'^backup/$', views.backupView, name='backup_maintain'),
    url(r'^backup/set/$', views.backupSetView, name='backupset_maintain'),
    url(r'^log/$', views.logView, name='log_maintain'),
    url(r'^isolate/$', views.isolateView, name='isolate_maintain'),
    url(r'^isolate/ajax$', views.isolateAjaxView, name='isolate_ajax_maintain'),
]

Linux-Operation0605/operation/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^operation/', include('operation.proxy_urls')),
]

Linux-Operation0605/app/maintain/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import smart_str
from app.maintain import choices
from lib.models import ZeroDateTimeField

# ext_sequester_mail
class ExtSquesterMail(models.Model):

    ident = models.CharField(u"邮件标识", max_length=25, null=True, blank=True)
    datetime = ZeroDateTimeField(u"隔离时间", null=False, blank=False)
    sender = models.CharField(u"发件人", max_length=80, null=True, blank=True)
    recipient = models.TextField(u"收件人", null=True, blank=True)
    mailsize = models.IntegerField(u'邮件大小', default=0)
    subject = models.CharField(u"主题", max_length=300, null=True, blank=True)
    attachment = models.SmallIntegerField(u"附件", null=True, blank=True)
    savepath = models.TextField(u"保存路径", null=True, blank=True)
    status = models.CharField(u"主题", max_length=20, default="wait", choices=choices.ISOLATE_STATUS, null=True, blank=True)
    reason = models.CharField(u"隔离原因", max_length=50, null=True, blank=True)
    detail = models.TextField(u"详情", null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'ext_sequester_mail'

    def __str__(self):
        return smart_str(self.ident)

    __repr__ = __str__

    @property
    def get_datetime(self):
        if not self.datetime:
            if self.datetime:
                return self.datetime.strftime('%Y-%m-%d %H:%M:%S')
            return "unknown"
        return self.datetime.strftime('%Y-%m-%d %H:%M:%S')

Linux-Operation0605/app/maintain/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import time
from django import forms
from app.maintain import choices
from app.core.models import CoreConfig, Mailbox
from django.utils.translation import ugettext_lazy as _

from lib import validators
from lib.forms import BaseFied, DotDict
from lib.tools import clear_redis_cache

class MailSearchForm(forms.Form):
    mail_status = forms.ChoiceField(label=u'状态', choices=choices.ISOLATE_STATUS_R, required=False, initial="wait")
    mail_sender = forms.CharField(label=u'发件人', max_length=80, required=False, widget=forms.TextInput(attrs={'size':12, 'placeholder': u""}))
    mail_sender_not = forms.CharField(label=u'发件人不包含', max_length=80, required=False, widget=forms.TextInput(attrs={'size':12, 'placeholder': u""}))
    mail_recipient = forms.CharField(label=u'收件人', max_length=80, required=False, widget=forms.TextInput(attrs={'size':12}))
    mail_subject = forms.CharField(label=u'主题', max_length=80, required=False, widget=forms.TextInput(attrs={'size':12}))
    mail_reason = forms.CharField(label=u'隔离原因', max_length=50, required=False, widget=forms.TextInput(attrs={'size':12}))
    mail_detail = forms.CharField(label=u'详情', max_length=80, required=False, widget=forms.TextInput(attrs={'size':12}))


class BackupSetForm(forms.Form):

    DATA_TYPE_CHOICES = choices.DATA_TYPE_CHOICES
    BACKUP_TYPE = choices.BACKUP_TYPE
    BACKUP_MONTH = choices.BACKUP_MONTH
    BACKUP_DAY = choices.BACKUP_DAY
    BACKUP_WEEK = choices.BACKUP_WEEK
    BACKUP_HOUR = choices.BACKUP_HOUR
    BACKUP_MINUTE = choices.BACKUP_MINUTE

    path = forms.CharField(label=u'保存路径', max_length=300, required=True, initial=u"/usr/local/u-mail/data/backup/",
                           help_text=u"注：备份数据的保存路径，请填写绝对路径；默认为“/usr/local/u-mail/data/backup/”！")
    data = forms.MultipleChoiceField(label=u'数据类型', required=True, choices=DATA_TYPE_CHOICES, initial=["database", "maildata"],
                                     help_text=u"可多选，按住Ctrl多选。", widget=forms.CheckboxSelectMultiple,) #widget=forms.CheckboxSelectMultiple,
    count = forms.IntegerField(label=u"保留备份数量", initial=10, required=True, help_text=u"留注：当备份的数据超过此限制时，将会删除旧的备份数据！ ")
    # 备份周期
    type = forms.ChoiceField(label=u"备份周期", required=True, choices=BACKUP_TYPE, initial="month")
    cycle = forms.IntegerField(label=u"Cycle", required=True, initial=1)
    # 备份时间
    month = forms.ChoiceField(label=u"Month", required=False, choices=BACKUP_MONTH)
    date =  forms.ChoiceField(label=u"Day", required=False, choices=BACKUP_DAY)
    week =  forms.ChoiceField(label=u"Week", required=False, choices=BACKUP_WEEK)
    hour =  forms.ChoiceField(label=u"Hour", required=False, choices=BACKUP_HOUR)
    minute =  forms.ChoiceField(label=u"Minute", required=False, choices=BACKUP_MINUTE)

    def clean_path(self):
        data = self.cleaned_data['path'].strip()
        if not data:
            raise forms.ValidationError(_(u"请填写保存路径"))
        return data

    def clean_count(self):
        data = self.cleaned_data['count']
        data = data and int(data) or 0
        if data<=0:
            raise forms.ValidationError(_(u"备份数量必须大于等于1"))
        return data

    def clean_cycle(self):
        data = self.cleaned_data['cycle']
        data = data and int(data) or 0
        if data<=0:
            raise forms.ValidationError(_(u"备份周期必须大于等于1"))
        return data

    def save(self):
        path = self.cleaned_data['path']
        data = self.cleaned_data['data']
        count = self.cleaned_data['count']
        ltype = self.cleaned_data['type']
        cycle = self.cleaned_data['cycle']

        week=""
        month=""
        date=""
        hour=""
        if ltype == "hour":
            minute = self.cleaned_data['minute']
        elif ltype == "day":
            minute = self.cleaned_data['minute']
            hour = self.cleaned_data['hour']
        elif ltype == "week":
            minute = self.cleaned_data['minute']
            hour = self.cleaned_data['hour']
            week = self.cleaned_data['week']
        elif ltype == "month":
            minute = self.cleaned_data['minute']
            hour = self.cleaned_data['hour']
            date = self.cleaned_data['date']
        else:
            minute = self.cleaned_data['minute']
            hour = self.cleaned_data['hour']
            date = self.cleaned_data['date']
            month = self.cleaned_data['month']
        CoreConfig.saveFuction(function="auto_backup", enabled=None, param=json.dumps({
            "path": path, "data": data, "count": count, "cycle": cycle, "type": ltype,
            "month": month, "date": date, "week": week, "hour": hour, "minute": minute,
        }), withenabled=False)

        clear_redis_cache()

Linux-Operation0605/app/maintain/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import re
import json
import pytz
import datetime
import subprocess
try:
    import cStringIO as StringIO
except:
    import StringIO

from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.contrib import messages
from django.template.response import TemplateResponse
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from wsgiref.util import FileWrapper
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection
from django.db.models import Q

from app.core.models import CoreConfig, DomainAttr
from app.maintain.tools import getLogDesc, LogFormat, BackupFormat, generateRedisTaskID
from app.maintain.models import ExtSquesterMail
from app.maintain.choices import ISOLATE_STATUS_R
from app.maintain.forms import BackupSetForm, MailSearchForm
from app.maintain import sslopts,choices
from lib import validators
from lib.tools import create_task_trigger
from lib.licence import licence_required

#########################################
# SSL加密
@licence_required
def sslView(request):
    # ssl开关
    sslobj = CoreConfig.getFuctionObj('ssl')
    # 私钥数据
    keyobj = DomainAttr.getAttrObj(item="ssl_privatekey")
    value = keyobj.value or None
    # 签名请求数据
    sigobj = DomainAttr.getAttrObj(item="ssl_signrequest")
    # 证书
    certobj = DomainAttr.getAttrObj(item="ssl_certificate")
    if request.method == "POST":
        status = request.POST.get("status", "")
        if status == "generate":
            # 系统生成私钥
            if value:
                messages.add_message(request, messages.ERROR, u'私钥已存在，设置私钥失败!')
                return HttpResponseRedirect(reverse("ssl_maintain"))
            else:
                try:
                    privkey = sslopts.genPrivKey()
                    keyobj.value = privkey
                    keyobj.save()
                    messages.add_message(request, messages.SUCCESS, u'生成私钥成功')
                    return HttpResponseRedirect(reverse("ssl_maintain"))
                except:
                    messages.add_message(request, messages.ERROR, u'生成私钥失败,请重新生成')
                    return HttpResponseRedirect(reverse("ssl_maintain"))

        if status == "clear":
            # 清除私钥
            keyobj.value = ""
            keyobj.save()
            # 清空证书签名请求
            DomainAttr.emptyAttrObjValue(item="ssl_signrequest")
            # 清除证书
            DomainAttr.emptyAttrObjValue(item="ssl_certificate")
            messages.add_message(request, messages.SUCCESS, u'清除私钥成功')
            return HttpResponseRedirect(reverse("ssl_maintain"))

        if status == "export-signature":
            # 导出签名请求
            sigvalue = sigobj.value or None
            if not sigvalue:
                messages.add_message(request, messages.ERROR, u'签名请求 不存在')
                return HttpResponseRedirect(reverse("ssl_maintain"))
            else:
                try:
                    wrapper = FileWrapper(StringIO.StringIO(sigvalue))
                    response = HttpResponse(wrapper, content_type='application/octet-stream')
                    response['Content-Length'] = len(value)
                    response['Content-Disposition'] = 'attachment; filename=%s' % "ssl_signrequest.csr"
                    return response
                except:
                    messages.add_message(request, messages.ERROR, u'导出签名请求失败，请重新导出')
                    return HttpResponseRedirect(reverse("ssl_maintain"))

        if status == "clear-signature":
            # 清除签名请求
            DomainAttr.emptyAttrObjValue(item="ssl_signrequest")
            messages.add_message(request, messages.SUCCESS, u'清除签名请求成功')
            return HttpResponseRedirect(reverse("ssl_maintain"))

        if status == "cert-export":
            # 导出证书
            certvalue = certobj.value or None
            if not certvalue:
                messages.add_message(request, messages.ERROR, u'证书 不存在')
                return HttpResponseRedirect(reverse("ssl_maintain"))
            else:
                try:
                    wrapper = FileWrapper(StringIO.StringIO(certvalue))
                    response = HttpResponse(wrapper, content_type='application/octet-stream')
                    response['Content-Length'] = len(value)
                    response['Content-Disposition'] = 'attachment; filename=%s' % "ssl_certificate.crt"
                    return response
                except:
                    messages.add_message(request, messages.ERROR, u'导出证书失败，请重新导出')
                    return HttpResponseRedirect(reverse("ssl_maintain"))

        if status == "cert-clear":
            # 清除证书
            DomainAttr.emptyAttrObjValue(item="ssl_certificate")
            messages.add_message(request, messages.SUCCESS, u'清除证书成功成功')
            return HttpResponseRedirect(reverse("ssl_maintain"))

    is_verify = False
    signature = DomainAttr.getSignatureCache()
    if sigobj.value:
        is_verify, signature2 = sslopts.parseSignature(sigobj.value)
        if is_verify: signature = signature2

    is_ca = False
    cert_subject, sert_issuer=None, None
    if certobj.value:
        is_ca = True
        cert_subject, sert_issuer = sslopts.parseCert(certobj.value)

    return render(request, "maintain/ssl.html", context={
        "sslobj": sslobj,
        "keyValue": sslopts.getPrivateKeySize(bytes(value)) if value else None,
        "is_verify": is_verify,
        "signature": signature,

        "is_ca": is_ca,
        "cert_subject": cert_subject,
        "sert_issuer": sert_issuer,
    })


@licence_required
def sslEnableView(request):
    if request.method == "POST":
        ssl = request.POST.get("ssl", "-1")
        if ssl in ("1", "-1"):
            obj = CoreConfig.getFuctionObj('ssl')
            obj.enabled=ssl
            obj.save()

            redis = get_redis_connection()
            redis.rpush("task_queue:apply_setting", "ssl")
            messages.add_message(request, messages.SUCCESS, u'应用设置成功')
        else:
            messages.add_message(request, messages.ERROR, u'未知错误，操作失败!')
        return HttpResponseRedirect(reverse("ssl_maintain"))
    raise Http404


# 私钥导入导出
@licence_required
def sslPrivateView(request):
    if request.method == "POST":
        status = request.POST.get("sslkey_status", "")
        obj = DomainAttr.getAttrObj(item="ssl_privatekey")
        value = obj.value
        if status == "import":
            keywd = request.POST.get("sslkey_passwd_import", "").strip()
            keywd = keywd or None
            if value:
                messages.add_message(request, messages.ERROR, u'私钥已存在，设置私钥失败!')
                return HttpResponseRedirect(reverse("ssl_maintain"))
            else:
                try:
                    fileobj = request.FILES['sslkeyfile']
                    privkey = fileobj.read()
                    privkey = sslopts.importPrivKey(privkey, passwd=keywd)
                    obj.value = privkey
                    obj.save()
                    messages.add_message(request, messages.SUCCESS, u'导入私钥成功')
                    return HttpResponseRedirect(reverse("ssl_maintain"))
                except BaseException as e:
                    messages.add_message(request, messages.ERROR, u'导入私钥失败（保护密码错误、非密钥文件等）, 请重新导入！')
                    return HttpResponseRedirect(reverse("ssl_maintain"))
        if status == "export":
            keywd = request.POST.get("sslkey_passwd_export", "").strip()
            keywd = keywd or None
            if value:
                try:
                    privkey = sslopts.exportPrivKey(bytes(value), passwd=keywd)
                    wrapper = FileWrapper(StringIO.StringIO(privkey))
                    response = HttpResponse(wrapper, content_type='application/octet-stream')
                    response['Content-Length'] = sslopts.getPrivateKeySize(bytes(value))
                    response['Content-Disposition'] = 'attachment; filename=%s' % "ssl_private.key"
                    return response
                except BaseException as e:
                    messages.add_message(request, messages.ERROR, u'私钥不正确，请重新生成私钥导出!')
                    return HttpResponseRedirect(reverse("ssl_maintain"))
            else:
                messages.add_message(request, messages.ERROR, u'私钥不存在，导出失败!')
                return HttpResponseRedirect(reverse("ssl_maintain"))
        return HttpResponseRedirect(reverse("ssl_maintain"))
    raise Http404


# 生成签名请求
@licence_required
def sslSignatureView(request):
    if request.method == "POST":
        obj = DomainAttr.getAttrObj(item="ssl_signrequest")
        keyobj = DomainAttr.getAttrObj(item="ssl_privatekey")
        keyvalue = keyobj.value
        if obj.value:
            messages.add_message(request, messages.ERROR, u'证书签名请求已存在，生成证书签名请求失败!')
            return HttpResponseRedirect(reverse("ssl_maintain"))
        else:
            sig_domain = request.POST.get("sig_domain", "").strip()
            sig_organization = request.POST.get("sig_organization", "").strip()
            sig_depart = request.POST.get("sig_depart", "").strip()
            sig_province = request.POST.get("sig_province", "").strip()
            sig_locale = request.POST.get("sig_locale", "").strip()
            j = {}
            msg = []
            if not validators.check_domain(u"@{}".format(sig_domain)):
                msg.append(u"域名 填写错误")
            j.update(sig_domain=sig_domain)

            if not sig_organization:
                msg.append(u"单位/组织 不能为空")
            elif  not validators.check_English(sig_organization):
                msg.append(u"单位/组织 只能填写英文字符")
            j.update(sig_organization=sig_organization)

            if sig_depart and not validators.check_English(sig_depart):

Linux-Operation0605/app/maintain/templates/maintain/ajax_isolate.html
<td>{{ d.id }}</td>
<td>{{ number }}</td>
<td>{{ d.get_datetime|default_if_none:'' }}</td>
<td>{{ d.sender|default_if_none:'' }}</td>
<td>{{ d.recipient|default_if_none:'' }}</td>
<td>{{ d.subject|default_if_none:'' }}</td>
<td>{{ d.reason|default_if_none:'' }}</td>
<td>{{ d.detail|default_if_none:'' }}</td>
<td>{{ d.mailsize|filesizeformat }}</td>
<td>{{ d.get_status_display }}</td>

Linux-Operation0605/app/maintain/templates/maintain/backupset.html
{% extends 'base_site.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap %}

{% block title %} {% trans "备份参数设置" %} {% endblock %}

{% block breadcrumb %}
    <li> <a href="#">{% trans "系统维护" %}</a> </li>
    <li><a href="#">{% trans "备份数据" %}</a></li>
    <li class="active">{% trans "备份参数设置" %}</li>
{% endblock %}


{% block page-content %}
    <div class="row">
        <div class="space-12"></div>
        <div class="col-xs-12">
            <div class="page-header">
                <h1>{% trans "备份参数设置" %}</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <form class="form-horizontal" role="form" action="" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right" for="id_mail_server"></label>
                    <div class="col-sm-10">
                        <div class="col-xs-10 col-sm-6" style="padding-left: 0px;padding-right: 0px;">
                            <div class="page-header" style="padding-bottom: 7px;padding-top: 0px;">
                                <h1>{% trans "备份参数设置" %}</h1>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group {% if form.path.errors %} has-error {% endif %}">
                    <label class="col-sm-3 control-label no-padding-right" for="id_path"> 保存路径 </label>
                    <div class="col-sm-9">
                        <input type="text" maxlength="200" id="id_path" name="path" value="{{ form.cleaned_data.path }}" class="col-xs-10 col-sm-5" required/>
                        {% if form.path.errors %}
                            {% for error in form.path.errors %}
                                <div style="clear: both"><p class="errornote txt-color-red">{{ error|escape }}</p></div>
                            {% endfor %}
                        {% endif %}
                        <p class="help-block" style="clear: both">
                            注：备份数据的保存路径，请填写绝对路径；默认为“/usr/local/u-mail/data/backup/”！
                        </p>
                    </div>
                </div>

                <div class="form-group {% if form.data.errors %} has-error {% endif %}">
                    <label class="col-sm-3 control-label no-padding-right" for="id_data"> 数据类型 </label>
                    <div class="col-sm-9">
                        <label class=" control-label form-inline">
                            <label>
                                <input name="data" value="database" id="id_data_0" type="checkbox" {% if "database" in form.cleaned_data.data %}checked=""{% endif %}><span class="margin-left-5">数据库</span>
                            </label>
                            <label style="margin-left: 15px">
                                <input name="data" value="maildata" id="id_data_1" type="checkbox" {% if "maildata" in form.cleaned_data.data %}checked=""{% endif %}><span class="margin-left-5">邮件数据</span>
                            </label>
                            <label style="margin-left: 15px">
                                <input name="data" value="netdisk" id="id_data_2" type="checkbox" {% if "netdisk" in form.cleaned_data.data %}checked=""{% endif %}><span class="margin-left-5">网盘数据</span>
                            </label>
                        </label>
                        {% if form.data.errors %}
                            {% for error in form.data.errors %}
                                <div style="clear: both"><p class="errornote txt-color-red">{{ error|escape }}</p></div>
                            {% endfor %}
                        {% endif %}
                        <p class="help-block" style="clear: both">
                            可多选。
                        </p>
                    </div>
                </div>

                <div class="form-group {% if form.count.errors %} has-error {% endif %}">
                    <label class="col-sm-3 control-label no-padding-right" for="id_count"> 保留备份数量 </label>
                    <div class="col-sm-9">
                        <input name="count" value="{{ form.cleaned_data.count }}" required="" class=" col-xs-10 col-sm-5" id="id_count" type="number" required>
                        {% if form.count.errors %}
                            {% for error in form.count.errors %}
                                <div style="clear: both"><p class="errornote txt-color-red">{{ error|escape }}</p></div>
                            {% endfor %}
                        {% endif %}
                        <p class="help-block" style="clear: both">
                            备注：当备份的数据超过此限制时，将会删除旧的备份数据！
                        </p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label no-padding-right" for="id_mail_server"></label>
                    <div class="col-sm-10">
                        <div class="col-xs-10 col-sm-6" style="padding-left: 0px;padding-right: 0px;">
                            <div class="page-header" style="padding-bottom: 7px;padding-top: 0px;">
                                <h1>{% trans "自动备份设置" %}</h1>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group {% if form.cycle.errors %} has-error {% endif %}">
                    <label class="col-sm-3 control-label no-padding-right" for="id_type"> 备份周期 </label>
                    <div class="col-sm-9">
                        <label class=" ">
                            <label>
                                每隔<input name="cycle" value="{{ form.cleaned_data.cycle }}" required="" id="id_cycle" type="number" required>
                                <select id="id_type" name="type" onchange="onchangeType(this.value)" style="height: 34px;">
                                    {% for k, v in form.BACKUP_TYPE %}
                                        <option value="{{ k }}" {% if form.cleaned_data.type == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>备份一次
                            </label>
                            {% if form.cycle.errors %}
                                {% for error in form.cycle.errors %}
                                    <div style="clear: both"><p class="errornote txt-color-red">{{ error|escape }}</p></div>
                                {% endfor %}
                            {% endif %}

                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="id_cycle"> 备份时间 </label>
                    <div class="col-sm-9">
                        <label class=" control-label form-inline">

                            <label id="id_month_lable">
                                <select id="id_month" name="month">
                                    {% for k, v in form.BACKUP_MONTH %}
                                        <option value="{{ k }}" {% if form.cleaned_data.month == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>月
                            </label>

                            <label id="id_date_lable">
                                <select id="id_date" name="date">
                                    {% for k, v in form.BACKUP_DAY %}
                                        <option value="{{ k }}" {% if form.cleaned_data.date == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>日
                            </label>

                            <label id="id_week_lable">
                                周
                                <select id="id_week" name="week">
                                    {% for k, v in form.BACKUP_WEEK %}
                                        <option value="{{ k }}" {% if form.cleaned_data.week == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>
                            </label>

                            <label id="id_hour_lable">
                                <select id="id_hour" name="hour">
                                    {% for k, v in form.BACKUP_HOUR %}
                                        <option value="{{ k }}" {% if form.cleaned_data.hour == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>点
                            </label>

                            <label id="id_minute_lable">
                                <select id="id_minute" name="minute">
                                    {% for k, v in form.BACKUP_MINUTE %}
                                        <option value="{{ k }}" {% if form.cleaned_data.minute == k %}selected{% endif %}>{{ v }}</option>
                                    {% endfor %}
                                </select>分
                            </label>

                        </label>
                    </div>
                </div>

                <div class="clearfix form-actions">
                    <div class="col-md-offset-3 col-md-9">
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            保存
                        </button>
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            重置
                        </button>

                        <a type="button" class="btn btn-link" href="{% url 'backup_maintain' %}">取消</a>

                    </div>
                </div>

            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="col-md-offset-2 col-md-10">
                <p><strong><span style="color:#FF0000;"><strong><span style="color:#FF0000;">备注:</span></strong><br></span></strong></p>
                <p>备份数据的保存路径需要先建立好，并且给予<span class="c_blue">umail</span>用户写权限（设置目录权限为777或将目录属主设为umail）</p>
                <p>如果要使用自动备份功能，则需要先启用<strong>“综合功能配置-&gt;系统功能设置-&gt;数据备份开关”</strong>功能</p>
            </div>
        </div>
    </div>
{% endblock %}


{% block css_block %}
    <style>
        .margin-left-5{margin-left: 5px;}
    </style>
{% endblock %}


{% block my_jsblock %}
    <script>

        $(function () {
            onchangeType('{{ form.cleaned_data.type }}');
        });

        function onchangeType(value){
            if (value == "year"){
                $("#id_month_lable").removeClass("display-none");
                $("#id_date_lable").removeClass("display-none");
                $("#id_week_lable").addClass("display-none");
                $("#id_hour_lable").removeClass("display-none");
                $("#id_minute_lable").removeClass("display-none");
            } else if ( value == "month" ) {
                $("#id_month_lable").addClass("display-none");
                $("#id_date_lable").removeClass("display-none");
                $("#id_week_lable").addClass("display-none");
                $("#id_hour_lable").removeClass("display-none");
                $("#id_minute_lable").removeClass("display-none");
            } else if ( value == "week" ) {
                $("#id_month_lable").addClass("display-none");
                $("#id_date_lable").addClass("display-none");
                $("#id_week_lable").removeClass("display-none");
                $("#id_hour_lable").removeClass("display-none");
                $("#id_minute_lable").removeClass("display-none");
            } else if ( value == "day" ) {
                $("#id_month_lable").addClass("display-none");
                $("#id_date_lable").addClass("display-none");
                $("#id_week_lable").addClass("display-none");
                $("#id_hour_lable").removeClass("display-none");
                $("#id_minute_lable").removeClass("display-none");
            } else if ( value == "hour" ) {
                $("#id_month_lable").addClass("display-none");
                $("#id_date_lable").addClass("display-none");
                $("#id_week_lable").addClass("display-none");
                $("#id_hour_lable").addClass("display-none");
                $("#id_minute_lable").removeClass("display-none");
            }
        }
    </script>
{% endblock %}